### ISSUE TITLE
Can't Import Projects

### ISSUE THREAD

**Issue by agieocean** [GoodAI/BrainSimulatorCodeSamples#1]
When I attempt to load either **jtc_bipedal.brain** or **pid_pendulum.brain** into Brain Simulator I get the following:

```
[ERROR] Project import failed: '>' is an unexpected token. The expected token is '='. Line 33, position 71.
```

**Comment by PremekPaska** [comment]
Hi, thanks for the report. However, I'm unable to reproduce it. Can you please describe exact steps to reproduce the problem?

Does it happen when you import it to any project (even empty one)? Or only when you import to a specific project?

**Comment by agieocean** [comment]
I apologize for the delayed reply.

I receive this error when I try to open the projects by using either Import or Open Project from the File dropdown menu.

It happens when I try to import jtc_bipedal.brain or pid_pendulum.brain both of these report the same error.

**Comment by PremekPaska** [comment]
It is possible that the files are damaged in some way. Did you try to get them from github again? https://github.com/GoodAI/BrainSimulatorSampleProjects/tree/master/Motor

If it does not help, please send me the files to premysl.paska@keenswh.com

**Comment by PremekPaska** [comment]
The described files are not valid brain projects, they are HTML pages. Please make sure that you use the "Raw" button on the page to download a file. Even better is cloning all repository using a Git client.
